[workspace]
members=["game", "engine", "aseprite"]

[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "./common" }
notify = "5"
sdl2 = "0.34.0"
once_cell = "1.13.0"