[package]
name = "nand2tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path="./engine" }
bevy_ecs = "0.14.0"
nalgebra-glm = "0.19.0"