[package]
name = "aseprite"
version = "0.1.0"
edition = "2021"

[dependencies]
 aseprite-loader = "0.3.4"
flate2 = "1.0"
png ="0.17.16"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"

